[package]
name = "nsis-fn"
version = "0.0.0"
edition = "2021"
license-file = "LICENSE"

[lib]
proc-macro = true
path = "Source/lib.rs"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
